name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          yarn install

      - name: Build Android
        run: |
          cd packages/mobile-app
          yarn android:build

      - name: Build iOS
        run: |
          cd packages/mobile-app
          yarn ios:build

      - name: Test
        run: |
          yarn test

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v1
        with:
          args: deploy --only hosting

